spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
        - name: Retry
          args:
            retries: 1
            statuses: SERVICE_UNAVAILABLE
            methods: POST
      routes:
        - id: vets-service
          uri: lb://vets-service
          predicates:
            - Path=/api/vet/**
          filters:
            - StripPrefix=2
        - id: visits-service
          uri: lb://visits-service
          predicates:
            - Path=/api/visit/**
          filters:
            - StripPrefix=2
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: genai-service
          uri: lb://genai-service
          predicates:
            - Path=/api/genai/**
          filters:
            - StripPrefix=2
            - CircuitBreaker=name=genaiCircuitBreaker,fallbackUri=/fallback
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      enabled: true
      endpoint: "http://zipkin.tracing.svc.cluster.local:9411/api/v2/spans"

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

  observations:
    key-values:
      service.name: ${spring.application.name:api-gateway}
      namespace: ${NAMESPACE:default}

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}){faint} %clr(%5p) level="%p" time="%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}" service="${spring.application.name}" traceId="%X{traceId:-}" spanId="%X{spanId:-}" thread="%t" logger="%logger{39}" message="%m"%n'
    file: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX} level="%p" time="%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}" service="${spring.application.name}" traceId="%X{traceId:-}" spanId="%X{spanId:-}" thread="%t" logger="%logger{39}" message="%m"%n'
  level:
    io.micrometer.tracing: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    org.springframework.cloud.sleuth.autoconfig: DEBUG
    org.springframework.web: DEBUG
  charset:
    console: UTF-8
    file: UTF-8
