server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tondeptrai23/spring-petclinic-microservices-config
          default-label: main
        native:
          search-locations: file:///${GIT_REPO}  


